# Generated by Django 2.0.6 on 2019-11-04 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promptagram_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptagrammodel',
            name='foreignKeyUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
