# Generated by Django 2.0.6 on 2019-11-05 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promptagram_app', '0002_auto_20191104_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='promptagrammodel',
            name='foreignKeyUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='promptagram_app.UserModel'),
        ),
    ]
