# Generated by Django 2.0.6 on 2019-11-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptagram_app', '0003_auto_20191105_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
